# cmds.yaml
# author: borysn
# license: MIT

#############
# ddBuilder #
#############
ddBuilder:

  #######
  # cmd #
  #######
  cmd:
    # help
    help:
      cmd: "help"
      alias:
        - "h"
        - "-h"
        - "--help"
      description:
        - "show help"
      usage:
        - "$ dd-builder h"
    # build
    build:
      cmd: "build"
      alias:
        - "b"
        - "-b"
        - "--build"
      description:
        - "build desktop dialogue"
      usage:
        - "$ dd-builder b <dir>"
