# cmds.yaml
# author: borysn
# license: MIT

#############
# ddBuilder #
#############
ddBuilder:

  ########
  # cmds #
  ########
  cmds:
    # help
    help:
      name: "help"
      alias:
        - "h"
        - "-h"
        - "--help"
      description:
        - "show help"
      usage:
        - "$ dd-builder h"
    # build
    build:
      name: "build"
      alias:
        - "b"
        - "-b"
        - "--build"
      description:
        - "build desktop dialogue"
      usage:
        - "$ dd-builder b <dir>"
